version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: eventier_mysql
    ports:
      - "33060:3306"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: eventier
      MYSQL_USER: eventier
      MYSQL_PASSWORD: eventier
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: eventier_php
    restart: always
    links:
      - mysql
    volumes:
      - "./app:/app"
    depends_on:
      - mysql

  nginx:
    image: nginx:1.9.10
    container_name: eventier_nginx
    volumes:
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - ./app/public:/app/public
    links:
      - php-fpm
    ports:
      - "8014:80"

